uploads = []
outputs = []

[[generated]]
id = "H_RbcR5jst3vp9lIY-X_u"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "PNo6F9RX65KOLX8ljFHeW"
uri = "file://artifacts/mobile/assets/images/splash-icon.png"
type = "image"
title = "generated_image"
